customhost = "employee.cmgkvjcxorcf.ap-south-1.rds.amazonaws.com"
customuser = "sblpratibha"
custompass = "pratibha123"
customdb = "employee"
custombucket = "addinemployee"
customregion = "ap-south-1"
